### ISSUE TITLE
Script downloads empty files

### ISSUE THREAD

**Issue by jacop5** [DanyB0/nhenty#1]
After downloading any doujin, none of the files are actually written. In fact, every file's size is 0 KB and none of them can be viewed.
<img width="705" alt="Schermata 2021-12-28 alle 03 17 15" src="https://user-images.githubusercontent.com/96621577/147520574-5e45196e-1711-4554-a0fa-119439565218.png">

**Comment by DanyB0** [comment]
It should be fixed, let me know if there are other issues.
(The quality of the images is low, when I have time I'll improve it)
